# 예외 처리 미루기
## 예외 처리를 미루는 throw 사용하기
### FileInputStream을 생성했을 때 예외 처리 방법은 두 가지 있었다.
### try-catch문으로 바꾸는 방법은 이전에 다루었음으로 throw 선언을 추가하는 방법을 알아보자.
### throws 선언을 추가하는 것은 예외를 해당 메서드에서 처리하지 않고 미룬 후 메서드를 호출하여 사용하는 부분에서 예외를 처리하는 방법이다.
```java
package exception;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class ThrowsException {
	public Class loadClass(String fileName, String className) throws FileNotFoundException, ClassNotFoundException {
		FileInputStream fis = new FileInputStream(fileName);	//FileNotFoundException 발생 가능
		Class c = Class.forName(className);						//ClassNotFoundException 발생 가능
		return c;
	}
	
	public static void main(String[] args) {
		ThrowsException test = new ThrowsException();
		test.loadClass("a.text", "java.lang.String");	//메서드를 호출할 때 예외를 처리함
	}
}
```
### loadClass() 메서드는 FileInputStream을 열고 Class를 동적으로 로딩하여 반환한다.
### 파일을 열 때는 FileNotFoundException이 발생할 수 있고, 클래스를 로딩할 때는 ClassNotFoundException이 발생할 수 있다.
### 하지면 처리를 미루겠다는 뜻의 throws를 메서드의 선언부에 추가해주었다.
## throws를 활용하여 예외 처리 미루기
### 예외를 처리하지 않고 미룬다고 선언하면, 그 메서르를 호출하여 사용하는 부분에서 예외처리를 해야 한다.
### main() 함수에서 test.loadClass는 loadClass() 메서드를 호출하는 부분이다.
### 그렇기에 빨간색 줄로 오류가 표시되고, 함수 선언 부분에 throws를 추가하여 예외처리를 미룬다는 것과 여러 예외를 한번에 처리하는 방법, 그리고 예외 상황마다 처리하는 방법을 알려준다.
### main() 함수엣 미룬 예외 처리는 main() 함수를 호출하는 JVM으로 보내진다.
### 즉 예외를 처리하는 것이 아니라 대부분의 프로그램이 비정상 종료된다.
### 따라서 여러 예외를 한번에 처리하거나, 예외 상황마다 처리하는 것이 좋다.
### 만약 Surround with try/multi-catch(여러 예외를 한번에 처리하기)를 선택하면 다음과 같이 코드가 생성된다.
```java
public static void main(String[] args) {
    ThrowsException test = new ThrowsException();
    try {
        test.loadClass("a.text", "java.lang.String");
    } catch (FileNotFoundException | ClassNotFoundException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
```
### 이 옵션은 하나의 catch문에서 여러 예외를 한 문장으로 처리하겠다는 뜻이다.
### 그렇지 않고 각 상황마다 예외 처리를 하려면 Surround with try/catch를 선택하면 된다.
```java
public static void main(String[] args) {
    ThrowsException test = new ThrowsException();
    try {
        test.loadClass("a.text", "java.lang.String");
    } catch (FileNotFoundException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } catch (ClassNotFoundException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
```
### 그러면 예외 상황의 수만큼 catch문이 생성된다.
### 각 예외 상황마다 다른 방식으로 처리해야 하고 로그도 다르게 남겨야 하는경우라면 이 옵션을 사용한다.
---
### 예외가 발생한 메서드에서 그 예외를 바로 처리할 것인지, 아니면 미루어서 그 메서드를 호출하여 사용하는 부분에서 처리할 것인지는 프로그램 상황에 따라 다를 수 있다.
### 만약 어떤 메서드가 다른 여러 코드에서 호출되어 사용된다면 호출하는 코드의 상황에 맞게 로그를 남기거나 예외 처리를 하는 것이 더 좋다.
### 따라서 이런 경우에는 메서드를 호출하는 부분에서 예외 처리를 하도록 미루는 것이 합리적이다.
## 다중 예외 처리
### 여러 catch문을 한꺼번에 사용하는 경우에 각 catch 블록은 각각의 예외 처리를 담당한다.
### 그런데 문법적으로 반드시 예외를 처리를 해야 하는 경우 이외에도 예외 처리를 해야 할 때가 있다.
### 예를들어 배열을 사용할 때 배열의 크기보다 큰 위치, 즉 요소가 존재하지 않는 위치로 접근하는 경우에 RuntimeException 중 ArrayIndexOutOfBoundsException이 발생한다.
### 이 예외는 컴파일러에 의해 체크되지 않는다.
### 이렇게 어떤 예외가 발생할지 미리 알 수 없지만 모든 예외 상황을 처리하고자 한다면 맨 마지막 부분에 Exception 클래스를 활용하여 catch 블록을 추가한다.
```java
package exception;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class ThrowsException {
	public Class loadClass(String fileName, String className) throws FileNotFoundException, ClassNotFoundException {
		FileInputStream fis = new FileInputStream(fileName);	//FileNotFoundException 발생 가능
		Class c = Class.forName(className);						//ClassNotFoundException 발생 가능
		return c;
	}
	
	public static void main(String[] args) {
		ThrowsException test = new ThrowsException();
		try {
			test.loadClass("a.text", "java.lang.String");
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (Exception e) {		//Exception 클래스로 그 외 예외 상황 처리
		e.printStackTrace();
		}
	}
}

```
### Exception 클래스는 모든 예외 클래스의 최상위 클래스이다.
### 따라서 다른 catch 블록에 선언한 것 이외의 예외가 발생하더라도 Exception 클래스로 자동 형 변환된다.
## 다중 예외 처리에서 주의사항
### 예외는 catch문을 선언한 순서대로 검사한다.
### 따라서 맨 위에 catch(Exception e) 문장을 쓰면 발생하는 모든 예외 클래스는 Exception 상위 클래스로 자동 형 변환되어 오류가 발생한다.
```java
public static void main(String[] args) {
    ThrowsException test = new ThrowsException();
    try {
        test.loadClass("a.text", "java.lang.String");
    } catch (Exception e) {		//Exception e 이외의 클래스에 오류 발생
        e.printStackTrace();
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    } 
}
```
### 기본 예외를 처리하는 Exception 클래스에 의해 모든 예외가 처리되므로 ClassNotFoundException이나 FileNotFoundException 문장에는 예외가 도달할 일이 없어 컴파일 오류가 발생한다.
### 따라서 기본 예외 처리를 하는 Exception 클래스 블록은 여러 예외 처리 블록의 가장 아래에 놓아야 한다.